### ISSUE TITLE
Landmarks Size

### ISSUE THREAD

**Issue by xingtracy** [avyan-k/MAIS-202-F2023-ASL-Processing#2]
The landmark size from the web app input doesn't fit in the MLP model . This is the error code. The root of the error is from the `app.py` file in the `getLetter()` method

```
x = F.leaky_relu(layer(x))
  File "/Users/tatax/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/tatax/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/tatax/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: linear(): input and weight.T shapes cannot be multiplied (4x2 and 42x64)
```

**Comment by avyan-k** [comment]
Just to confirm, getLetter() return the letter prediction, position in the alphabet, or the tensor of probabilities (ie if the prediction is 'A', should it return 'A', 1, or whatever the mlp returns)?

**Comment by xingtracy** [comment]
getLetter should return the predicted letter. You can use the alphabet array in the capture_input to get letter from index

**Comment by avyan-k** [comment]
Alright, the webapp does seem to work on my machine for now. I have pushed the working version. It imports from predict instead of capture_input though, that may have to be change. Also, I removed the DataLoader section of getLetter() for simplicity, we can put it back from the previous commit if needed

**Comment by xingtracy** [comment]
the webapp most likely doesn't work because you need to set up the flask environment
